--liquibase formatted sql
--changeset santhosh:7

CREATE TABLE `family_details` (
  `id` int NOT NULL AUTO_INCREMENT,
  `family_id` varchar(15) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `area_details` int NOT NULL,
  `door_no` varchar(200) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `respondent_name` varchar(300) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `mobile_number` varchar(15) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `status_of_house` int DEFAULT NULL,
  `type_of_house` int DEFAULT NULL,
  `wet_land_in_acres` varchar(1000) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT 'N/A',
  `dry_land_in_acres` varchar(1000) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT 'N/A',
  `motor_vechicles` varchar(1000) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT 'N/A',
  `one_wheeler` int DEFAULT NULL,
  `two_wheeler` int DEFAULT NULL,
  `three_wheeler` int DEFAULT NULL,
  `four_wheeler` int DEFAULT NULL,
  `no_other_vechicles` int DEFAULT NULL,
  `other_vechicles_details` varchar(1000) DEFAULT 'N/A',
  `livestock_details` varchar(1000) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT 'N/A',
  `hen` int DEFAULT NULL,
  `cow` int DEFAULT NULL,
  `pig` int DEFAULT NULL,
  `buffalo` int DEFAULT NULL,
  `goat` int DEFAULT NULL,
  `no_other_livestock` int DEFAULT NULL,
  `other_livestock_details` varchar(1000) DEFAULT 'N/A',
  `toilet_facility_at_home` varchar(5) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT 'N/A',
  `deleted_by` int DEFAULT NULL,
  `is_deleted` varchar(5) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT '',
  `created_by` int DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` int DEFAULT NULL,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=34800 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
